"""initial schema

Revision ID: 8492c01f2307
Revises: 
Create Date: 2026-05-30 00:41:31.570629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8492c01f2307'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('baseline_start', sa.DateTime(), nullable=True),
    sa.Column('baseline_finish', sa.DateTime(), nullable=True),
    sa.Column('control_start', sa.DateTime(), nullable=True),
    sa.Column('control_finish', sa.DateTime(), nullable=True),
    sa.Column('base_currency_code', sa.String(length=3), nullable=False),
    sa.Column('multi_currency', sa.Boolean(), nullable=False),
    sa.Column('cost_budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_actual', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_eac', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('system_role', sa.Enum('admin', 'instructor', 'student', name='system_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('class_code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cbs_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code')
    )
    op.create_index(op.f('ix_cbs_nodes_project_id'), 'cbs_nodes', ['project_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('contract_code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'awarded', 'active', 'closed', 'cancelled', name='contract_status'), nullable=False),
    sa.Column('price_type', sa.Enum('lump_sum', 'unit_rate', 'reimbursable', 'time_and_materials', name='price_type'), nullable=False),
    sa.Column('award_date', sa.DateTime(), nullable=True),
    sa.Column('mobilize_date', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hours', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ceiling', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('retention_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('adv_payment_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'contract_code')
    )
    op.create_index(op.f('ix_contracts_project_id'), 'contracts', ['project_id'], unique=False)
    op.create_index(op.f('ix_contracts_vendor_id'), 'contracts', ['vendor_id'], unique=False)
    op.create_table('curves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('curve_type', sa.Enum('linear', 's_curve', 'front_loaded', 'back_loaded', 'milestone', name='curve_type'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code')
    )
    op.create_table('periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('fiscal_year_end', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code')
    )
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('project_role', sa.Enum('pm', 'cost_engineer', 'scheduler', 'controller', 'viewer', name='project_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id')
    )
    op.create_table('wbs_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code')
    )
    op.create_index(op.f('ix_wbs_nodes_project_id'), 'wbs_nodes', ['project_id'], unique=False)
    op.create_table('change_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('change_code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('trend', 'submitted', 'approved', 'rejected', 'withdrawn', name='change_status'), nullable=False),
    sa.Column('reason', sa.Enum('scope', 'design', 'site_conditions', 'schedule', 'rate', 'other', name='change_reason'), nullable=True),
    sa.Column('impact', sa.Enum('cost', 'schedule', 'both', 'none', name='change_impact'), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('added_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pct_complete', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'change_code')
    )
    op.create_table('contract_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('item_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('hours', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'item_no')
    )
    op.create_table('cost_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('account_code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('master_account_id', sa.UUID(), nullable=True),
    sa.Column('wbs_node_id', sa.UUID(), nullable=True),
    sa.Column('cbs_node_id', sa.UUID(), nullable=True),
    sa.Column('curve_id', sa.UUID(), nullable=True),
    sa.Column('discipline', sa.Text(), nullable=True),
    sa.Column('dim_1', sa.Text(), nullable=True),
    sa.Column('dim_2', sa.Text(), nullable=True),
    sa.Column('dim_3', sa.Text(), nullable=True),
    sa.Column('dim_4', sa.Text(), nullable=True),
    sa.Column('dim_5', sa.Text(), nullable=True),
    sa.Column('pct_complete', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('pct_complete_method', sa.Enum('manual', 'weighted_steps', 'rules_of_credit', 'level_of_effort', 'fifty_fifty', name='pct_method'), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('baseline_start', sa.DateTime(), nullable=True),
    sa.Column('baseline_finish', sa.DateTime(), nullable=True),
    sa.Column('control_start', sa.DateTime(), nullable=True),
    sa.Column('control_finish', sa.DateTime(), nullable=True),
    sa.Column('cost_budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_earned', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_actual', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_incurred', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_commitment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_open_commit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_etc', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_eac', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hour_budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hour_earned', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hour_actual', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hour_etc', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hour_eac', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_bac_baseline', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_bac_approved', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_bac_control', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_bac_changes', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cf_adv_pay_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('cf_retention_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('cash_flow_lag', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cbs_node_id'], ['cbs_nodes.id'], ),
    sa.ForeignKeyConstraint(['curve_id'], ['curves.id'], ),
    sa.ForeignKeyConstraint(['master_account_id'], ['cost_accounts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wbs_node_id'], ['wbs_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'account_code')
    )
    op.create_index(op.f('ix_cost_accounts_cbs_node_id'), 'cost_accounts', ['cbs_node_id'], unique=False)
    op.create_index(op.f('ix_cost_accounts_master_account_id'), 'cost_accounts', ['master_account_id'], unique=False)
    op.create_index(op.f('ix_cost_accounts_project_id'), 'cost_accounts', ['project_id'], unique=False)
    op.create_index(op.f('ix_cost_accounts_wbs_node_id'), 'cost_accounts', ['wbs_node_id'], unique=False)
    op.create_table('currency_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate_to_base', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'currency_code')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('invoice_no', sa.Text(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'paid', 'rejected', name='invoice_status'), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cost_account_id', sa.UUID(), nullable=False),
    sa.Column('change_order_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity_unit', sa.Text(), nullable=True),
    sa.Column('hour_rate', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('hours', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('x_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('imported', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['change_order_id'], ['change_orders.id'], ),
    sa.ForeignKeyConstraint(['cost_account_id'], ['cost_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_lines_cost_account_id'), 'budget_lines', ['cost_account_id'], unique=False)
    op.create_table('change_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('change_order_id', sa.UUID(), nullable=False),
    sa.Column('cost_account_id', sa.UUID(), nullable=False),
    sa.Column('hour_impact', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_impact', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['change_order_id'], ['change_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_account_id'], ['cost_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_lines_cost_account_id'), 'change_lines', ['cost_account_id'], unique=False)
    op.create_table('commitments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('cost_account_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('x_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cost_account_id'], ['cost_accounts.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitments_cost_account_id'), 'commitments', ['cost_account_id'], unique=False)
    op.create_index(op.f('ix_commitments_period_id'), 'commitments', ['period_id'], unique=False)
    op.create_table('cost_account_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cost_account_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('budget_baseline', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_approved', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_control', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('earned', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('commitment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cash_flow', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('change_approved', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hour_budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hour_earned', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hour_actual', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cost_account_id'], ['cost_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cost_account_id', 'period_id')
    )
    op.create_index(op.f('ix_cost_account_periods_period_id'), 'cost_account_periods', ['period_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('cost_account_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('x_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cost_account_id'], ['cost_accounts.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_cost_account_id'), 'invoice_lines', ['cost_account_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_period_id'), 'invoice_lines', ['period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_lines_period_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_cost_account_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_cost_account_periods_period_id'), table_name='cost_account_periods')
    op.drop_table('cost_account_periods')
    op.drop_index(op.f('ix_commitments_period_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_cost_account_id'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_change_lines_cost_account_id'), table_name='change_lines')
    op.drop_table('change_lines')
    op.drop_index(op.f('ix_budget_lines_cost_account_id'), table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_table('invoices')
    op.drop_table('currency_rates')
    op.drop_index(op.f('ix_cost_accounts_wbs_node_id'), table_name='cost_accounts')
    op.drop_index(op.f('ix_cost_accounts_project_id'), table_name='cost_accounts')
    op.drop_index(op.f('ix_cost_accounts_master_account_id'), table_name='cost_accounts')
    op.drop_index(op.f('ix_cost_accounts_cbs_node_id'), table_name='cost_accounts')
    op.drop_table('cost_accounts')
    op.drop_table('contract_lines')
    op.drop_table('change_orders')
    op.drop_index(op.f('ix_wbs_nodes_project_id'), table_name='wbs_nodes')
    op.drop_table('wbs_nodes')
    op.drop_table('project_members')
    op.drop_table('periods')
    op.drop_table('curves')
    op.drop_index(op.f('ix_contracts_vendor_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_project_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_cbs_nodes_project_id'), table_name='cbs_nodes')
    op.drop_table('cbs_nodes')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
